name: Update Token

on: 
  push:
    branches: ["master"]
  schedule:
    - cron: '10 10 * * 1,4,6'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl
      run: |
        pip install requests
        pip install PyNaCl
    - name: update secrets
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        APP_NUM: ${{ secrets.APP_NUM }} 
        MS_TOKEN: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        MS_TOKEN_2: ${{ secrets.MS_TOKEN_2 }} 
        CLIENT_ID_2: ${{ secrets.CLIENT_ID_2 }}
        CLIENT_SECRET_2: ${{ secrets.CLIENT_SECRET_2 }}
        MS_TOKEN_3: ${{ secrets.MS_TOKEN_3 }} 
        CLIENT_ID_3: ${{ secrets.CLIENT_ID_3 }}
        CLIENT_SECRET_3: ${{ secrets.CLIENT_SECRET_3 }}
        MS_TOKEN_4: ${{ secrets.MS_TOKEN_4 }} 
        CLIENT_ID_4: ${{ secrets.CLIENT_ID_4 }}
        CLIENT_SECRET_4: ${{ secrets.CLIENT_SECRET_4 }}
        MS_TOKEN_5: ${{ secrets.MS_TOKEN_5 }} 
        CLIENT_ID_5: ${{ secrets.CLIENT_ID_5 }}
        CLIENT_SECRET_5: ${{ secrets.CLIENT_SECRET_5 }}
        MS_TOKEN_n: ${{ secrets.MS_TOKEN_n }} 
        CLIENT_ID_n: ${{ secrets.CLIENT_ID_n }}
        CLIENT_SECRET_n: ${{ secrets.CLIENT_SECRET_n }}
      run: |
        python updatetoken.py
